import os
import yaml
import json
import requests
import pandas as pd
import numpy as np
from pathlib import Path
from gen3.auth import Gen3Auth
from gen3.submission import Gen3Submission
import time 

def load_submission_sequence(config_path="submission_order.yaml"):
    with open(config_path, "r") as f: 
        config = yaml.safe_load(f)
    return config["submission_order"]

def main():
    endpoint = "https://gen3-dev.core.wits.ac.za"
    program = "MADIVA"
    # Define all valid projects in your cluster here
    active_projects = ["Agincourt", "Nairobi"] 

    ONE_TO_ONE_NODES = {"demographic"}  
    credentials_path = Path("credentials(2).json")

    print("Authenticating with Gen3 API...")
    auth = Gen3Auth(endpoint, refresh_file=str(credentials_path))
    sub_client = Gen3Submission(endpoint, auth)
    
    try:
        token = auth.get_access_token()
    except Exception as e:
        print(f"CRITICAL: Failed to retrieve access token: {e}")
        return
        
    headers = {
        "Authorization": f"bearer {token}",
        "Content-Type": "application/json"
    }

    # ================================================================
    # 1. FETCH UUIDS FOR ALL PROJECTS
    # ================================================================
    print("\nQuerying system graph to find internal UUIDs for all projects...")
    project_uuids = {}
    for proj in active_projects:
        gql_query = f'{{ project (code: "{proj}") {{ id }} }}'
        try:
            query_response = sub_client.query(gql_query)
            project_records = query_response.get("data", {}).get("project", [])
            if project_records:
                project_uuids[proj] = project_records[0]["id"]
                print(f"-> Resolved '{proj}' to UUID: {project_uuids[proj]}")
            else:
                print(f"⚠️ WARNING: Project '{proj}' could not be resolved. It may not exist in Gen3.")
        except Exception as gql_error:
            print(f"CRITICAL: GraphQL query failed for {proj}: {gql_error}")
            return

    # In-memory routing map to link subjects to their correct projects
    subject_routing_map = {}

    try:
        files_to_submit = load_submission_sequence("submission_order.yaml")
    except FileNotFoundError:
        print("CRITICAL: submission_order.yaml is missing.")
        return

    print(f"\nStarting sequential graph database Ingestion...")
    for target in files_to_submit:
        node_name = target["node"]
        file_path = Path(target["path"])
        
        if node_name == "project":
            continue

        print(f"\n[Processing] Node '{node_name}' from {file_path}")

        if not file_path.exists():
            print(f"Aborting: payload file missing at path: {file_path}")
            break

        try:
            # ================================================================
            # 2. Read the json payloads
            # ================================================================
            with open(file_path, 'r') as f:
                records = json.load(f)
            
            payloads_by_project = {proj: [] for proj in active_projects}

            # ================================================================
            # 3. GRAPH LINKAGE & ROUTING HARMONIZATION
            # ================================================================
            for record in records:
                target_project = None

                if node_name == "subject":
                    # Our ETL script generated 'projects.code', so we pop it from the dictionary
                    target_project = record.pop("projects.code", None)

                    if target_project and target_project in project_uuids:
                        # Set strict UUID link for the API
                        record["projects"] = {"id": project_uuids[target_project]}
                        
                        # Memorize this subject's project for future child nodes
                        subject_id = record.get("submitter_id")
                        if subject_id:
                            subject_routing_map[subject_id] = target_project
                            
                        payloads_by_project[target_project].append(record)
                    else:
                        print(f"Warning: Subject {record.get('submitter_id')} mapped to unknown project '{target_project}'.")

                else:
                    # For child nodes, extract the parent ID generated by our ETL script
                    parent_id = record.pop("subjects.submitter_id", None)
                    
                    if not parent_id:
                        print(f"Skipping a {node_name} record: No parent subject ID found.")
                        continue
                        
                    # Reconstruct the nested dictionary structural link required by the API
                    if node_name in ONE_TO_ONE_NODES:
                        record["subjects"] = {"submitter_id": parent_id}
                    else:
                        record["subjects"] = [{"submitter_id": parent_id}]

                    # Look up the correct project endpoint using our memory map
                    target_project = subject_routing_map.get(parent_id)
                    
                    if target_project and target_project in payloads_by_project:
                        payloads_by_project[target_project].append(record)
                    else:
                        print(f"Warning: Subject {parent_id} not found in routing map. Skipping child node.")

            # ================================================================
            # 4. STREAM PAYLOADS TO RESPECTIVE ENDPOINTS (CHUNKED)
            # ================================================================
            CHUNK_SIZE = 500 # Send n records at a time

            for proj, project_payload in payloads_by_project.items():
                if not project_payload:
                    continue 
                
                total_records = len(project_payload)
                print(f"  -> Submitting {total_records} records to {proj} endpoint in chunks of {CHUNK_SIZE}...")
                submission_url = f"{endpoint}/api/v0/submission/{program}/{proj}/"
                
                # Loop through the massive list in steps of CHUNK_SIZE
                for i in range(0, total_records, CHUNK_SIZE):
                    batch = project_payload[i:i + CHUNK_SIZE]
                    batch_num = (i // CHUNK_SIZE) + 1

# --- RETRIES ---
                    max_retry = 3
                    upload_success = False

                    for attempt in range(max_retry):
                        try:
                            # Bumped to 120s for heavy lab chunks
                            response = requests.put(submission_url, headers=headers, json=batch, timeout=120)

                            if response.status_code in [200, 201]:
                                print(f"     Success: Batch {batch_num} uploaded ({len(batch)} records).")
                                upload_success = True
                                break
                            else:
                                print(f"     WARNING: Batch {batch_num} failed (Code: {response.status_code})")
                            
                            # Catch the 400 errors and print ONLY the broken records
                            if response.status_code == 400:
                                try:
                                    error_data = response.json()
                                    entities = error_data.get("entities", [])

                                    invalid_entities = [ e for e in entities if not e.get("valid")]

                                    if invalid_entities:
                                        for entity in invalid_entities:
                                            bad_id = entity.get("unique_keys", [{}])[0].get("submitter_id", "Unknown")
                                            print(f"       -> Broken Record ID: {bad_id}")
                                            print(f"       -> Error: {entity.get('errors')}")
                                    else:
                                        print("        -> Gen3 Error Detail:")
                                        print(f"        {json.dumps(error_data, indent=2)}")
                                
                                except Exception as e:
                                    print(f"        -> Raw response: {response.text}")

                                time.sleep(3)

                        # THIS CATCHES THE TIMEOUT WITHOUT CRASHING
                        except requests.exceptions.Timeout:
                            print(f"     WARNING: Batch {batch_num} timed out (Attempt {attempt+1}/{max_retry}). Retrying...")
                            time.sleep(10)
                            continue  # Jumps to the next attempt in the loop
                            
                        # THIS CATCHES HARD NETWORK DROPS
                        except requests.exceptions.RequestException as e:
                            print(f"     WARNING: Network error on Batch {batch_num}: {e}")
                            time.sleep(10)
                            continue

                    if not upload_success:
                        print("     Aborting further chunks for this node to preserve data integrity.")
                        break  # Exits the OUTER chunk loop
                        
                    time.sleep(2)  # Standard throttle between successful batches
                        
        except Exception as error:
            print(f"CRITICAL ERROR processing node '{node_name}': {error}")
            break

if __name__ == "__main__":
    main()