"""
diff_missing_records.py v3

Compares each local payload file (as generated by your ETL pipeline) against
what Gen3 actually has ingested for that node/project, and writes out ONLY
the records that are missing — so you can resubmit a small targeted batch
instead of re-running the whole upload.

Root cause this addresses: your upload script's retry/abort logic silently
drops the remainder of a node's chunks once a batch hits a non-transient
400 error (e.g. bad node "type" or a malformed record). This script finds
exactly which submitter_ids never made it in, per node.

Usage:
    python3 diff_missing_records.py

Output:
    payloads/missing/payload_<node>_missing.json   (one per node with gaps)

Then feed those files back through your normal upload_data.py flow by
pointing submission_order.yaml at the *_missing.json files, or run them
as a one-off pass.
"""

import json
import time
from pathlib import Path
from gen3.auth import Gen3Auth
from gen3.submission import Gen3Submission
import yaml

# ================================================================
# CONFIG — match this to upload_data.py
# ================================================================
ENDPOINT = "https://gen3-dev.core.wits.ac.za"
PROGRAM = "MADIVA"
ACTIVE_PROJECTS = ["Agincourt", "Nairobi"]
CREDENTIALS_PATH = Path("credentials(2).json")
SUBMISSION_ORDER_PATH = "submission_order.yaml"
PAGE_SIZE = 1000  # Gen3/Peregrine commonly caps 'first' server-side around this
                   # value regardless of what's requested — keep this at or
                   # below the server cap so we always get full pages while
                   # data remains.
OUTPUT_DIR = Path("payloads/missing")

# Nodes where a subject can have multiple records (submitter_id is unique
# per record, not per subject) — same set your upload script treats as
# "not one-to-one".
ONE_TO_ONE_NODES = {"demographic"}


EXISTENCE_CHUNK_SIZE = 200  # how many submitter_ids to check per query


def existing_ids_from_known_set(sub_client, node, project_id, candidate_ids):
    """Check which of `candidate_ids` already exist in Gen3, WITHOUT pulling
    or sorting the whole table. Uses an equality filter on submitter_id,
    which hits the same unique index Postgres uses for the constraint
    check — cheap, indexed, no ORDER BY, no OFFSET, no full-table sort.

    This replaces paginated_submitter_ids for large nodes where a global
    sort (order_by_asc) was causing Peregrine to hang and get killed
    (exit 137) on ~1M-row tables like socioeconomic/medical_history.
    """
    candidate_ids = list(candidate_ids)
    found = set()

    for i in range(0, len(candidate_ids), EXISTENCE_CHUNK_SIZE):
        chunk = candidate_ids[i:i + EXISTENCE_CHUNK_SIZE]
        # GraphQL list literal for the IN-style equality filter
        id_list = json.dumps(chunk)
        gql_query = f'''
        {{
          {node} (project_id: "{project_id}", submitter_id: {id_list}, first: {EXISTENCE_CHUNK_SIZE}) {{
            submitter_id
          }}
        }}
        '''

        page = None
        for attempt in range(5):
            result = sub_client.query(gql_query)
            if "error" in result:
                wait = 5 * (attempt + 1)
                print(f"    [retry] {node} chunk {i}-{i+len(chunk)} -> {result['error']} "
                      f"(attempt {attempt + 1}/5, waiting {wait}s)")
                time.sleep(wait)
                continue
            if "data" not in result or result["data"].get(node) is None:
                wait = 5 * (attempt + 1)
                print(f"    [retry] {node} chunk {i}-{i+len(chunk)} -> unexpected response "
                      f"(attempt {attempt + 1}/5, waiting {wait}s)")
                time.sleep(wait)
                continue
            page = result["data"][node]
            break

        if page is None:
            raise RuntimeError(
                f"Giving up checking {node} existence chunk {i}-{i+len(chunk)} "
                f"(project_id={project_id}) after 5 failed attempts."
            )

        found.update(r["submitter_id"] for r in page)

        if (i // EXISTENCE_CHUNK_SIZE) % 20 == 0:
            print(f"    ...checked {i + len(chunk)}/{len(candidate_ids)} for {node}...")

    return found


def paginated_submitter_ids(sub_client, node, project_id):
    """Pull every submitter_id currently in Gen3 for a given node + project_id,
    paging so we never ask for an unbounded result set at once.

    IMPORTANT: explicitly sorts by 'id' (immutable UUID). Without an
    explicit ORDER BY, Postgres offset pagination is not guaranteed to
    return a stable row order across separate queries — rows can be
    skipped or double-counted between pages purely as a planner artifact,
    even with zero concurrent writes.

    Also treats a Peregrine 'error' response as a TRANSIENT failure, not
    as end-of-data. Silently swallowing an error page here would make a
    large table look nearly empty and generate a flood of false-positive
    "missing" records — exactly what happened on socioeconomic/
    medical_history when Peregrine returned 'service failure'.

    NOTE: for large nodes (socioeconomic, medical_history), prefer
    existing_ids_from_known_set instead — the global order_by_asc sort
    required here caused Peregrine to hang and get OOM/liveness-killed
    on ~1M-row tables. This function is kept for smaller nodes where a
    full listing (e.g. for the subject routing map) is still cheap."""
    ids = set()
    offset = 0
    max_retries = 5

    while True:
        gql_query = f'''
        {{
          {node} (project_id: "{project_id}", first: {PAGE_SIZE}, offset: {offset}, order_by_asc: "submitter_id") {{
            submitter_id
          }}
        }}
        '''

        page = None
        for attempt in range(max_retries):
            result = sub_client.query(gql_query)

            if "error" in result:
                wait = 5 * (attempt + 1)
                print(f"    [retry] {node} offset={offset} -> {result['error']} "
                      f"(attempt {attempt + 1}/{max_retries}, waiting {wait}s)")
                time.sleep(wait)
                continue

            if "data" not in result or result["data"].get(node) is None:
                wait = 5 * (attempt + 1)
                print(f"    [retry] {node} offset={offset} -> unexpected response {result} "
                      f"(attempt {attempt + 1}/{max_retries}, waiting {wait}s)")
                time.sleep(wait)
                continue

            page = result["data"][node]
            break

        if page is None:
            raise RuntimeError(
                f"Giving up on {node} (project_id={project_id}, offset={offset}) after "
                f"{max_retries} failed attempts. Refusing to report a partial count as "
                f"complete — check Peregrine/Postgres health before re-running."
            )

        if not page:
            # A genuinely empty page is the ONLY valid stop condition.
            # Do NOT stop just because len(page) < PAGE_SIZE — Peregrine
            # can silently cap 'first' below what was requested, which
            # previously caused pagination to quit after page 1 and
            # report large nodes as almost empty (e.g. demographic
            # Nairobi showing in_gen3=1000 instead of 11864).
            break

        ids.update(r["submitter_id"] for r in page)
        offset += len(page)

    return ids


# Nodes too large for a full sorted listing to be safe against Peregrine's
# current resource limits — use the indexed existence-check path instead.
LARGE_NODES = {"socioeconomic", "medical_history"}


def build_subject_routing_map(sub_client, project_uuids):
    """submitter_id -> project short name (e.g. 'Agincourt'), built straight
    from Gen3, same approach as the fixed upload_data.py.

    Also returns the raw per-project id sets so the main loop can reuse
    them for the 'subject' node's own diff, instead of re-querying Gen3
    a second time (which can drift if ingestion is happening concurrently)."""
    routing_map = {}
    subject_ids_by_project = {}
    for proj in project_uuids:
        project_id = f"{PROGRAM}-{proj}"
        ids = paginated_submitter_ids(sub_client, "subject", project_id)
        subject_ids_by_project[proj] = ids
        for sid in ids:
            routing_map[sid] = proj
        print(f"-> {proj}: {len(ids)} subjects currently in Gen3")
    return routing_map, subject_ids_by_project


def load_submission_sequence(config_path):
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    return config["submission_order"]


def main():
    print("Authenticating with Gen3 API...")
    auth = Gen3Auth(ENDPOINT, refresh_file=str(CREDENTIALS_PATH))
    sub_client = Gen3Submission(ENDPOINT, auth)

    # Resolve project UUIDs (not strictly needed for the diff, but keeps
    # this script self-contained / consistent with upload_data.py)
    project_uuids = {}
    for proj in ACTIVE_PROJECTS:
        gql_query = f'{{ project (code: "{proj}") {{ id }} }}'
        result = sub_client.query(gql_query)
        records = result.get("data", {}).get("project", [])
        if records:
            project_uuids[proj] = records[0]["id"]

    print("\nBuilding subject routing map from Gen3...")
    routing_map, subject_ids_by_project = build_subject_routing_map(sub_client, project_uuids)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    submission_sequence = load_submission_sequence(SUBMISSION_ORDER_PATH)

    print("\n" + "=" * 70)
    for target in submission_sequence:
        node = target["node"]
        path = Path(target["path"])

        if node == "project":
            continue
        if not path.exists():
            print(f"[{node}] SKIPPED — local file not found: {path}")
            continue

        with open(path, "r") as f:
            local_records = json.load(f)

        # Figure out which project each local record belongs to, and what
        # its comparison key is (submitter_id for subject; for child nodes
        # we still compare on the record's own submitter_id, since that's
        # what Gen3 stores/returns).
        local_by_project = {proj: [] for proj in ACTIVE_PROJECTS}
        unroutable = []

        for record in local_records:
            sid = record.get("submitter_id")
            if node == "subject":
                proj = record.get("projects.code")
            else:
                parent_id = record.get("subjects.submitter_id")
                proj = routing_map.get(parent_id)

            if proj and proj in local_by_project:
                local_by_project[proj].append((sid, record))
            else:
                unroutable.append(sid)

        missing_all = []
        for proj in ACTIVE_PROJECTS:
            if not local_by_project[proj]:
                continue
            project_id = f"{PROGRAM}-{proj}"
            local_ids = {sid for sid, _ in local_by_project[proj]}

            if node == "subject":
                # Reuse the set fetched during routing-map build instead of
                # re-querying — avoids double-counting drift if ingestion
                # is happening concurrently.
                gen3_ids = subject_ids_by_project.get(proj, set())
            elif node in LARGE_NODES:
                # These tables are too large for a safe global sort — check
                # only the specific IDs we care about via indexed equality
                # lookups instead of pulling/sorting the whole table.
                print(f"  Checking {len(local_ids)} known {node} IDs against Gen3 ({proj})...")
                gen3_ids = existing_ids_from_known_set(sub_client, node, project_id, local_ids)
            else:
                gen3_ids = paginated_submitter_ids(sub_client, node, project_id)

            missing_ids = local_ids - gen3_ids

            missing_records = [rec for sid, rec in local_by_project[proj] if sid in missing_ids]
            missing_all.extend(missing_records)

            print(f"[{node}] {proj}: local={len(local_ids)} in_gen3={len(gen3_ids & local_ids)} missing={len(missing_ids)}")

        if unroutable:
            print(f"[{node}] WARNING: {len(unroutable)} local records had no resolvable project/parent — check these manually: {unroutable[:10]}{' ...' if len(unroutable) > 10 else ''}")

        if missing_all:
            out_path = OUTPUT_DIR / f"payload_{node}_missing.json"
            with open(out_path, "w") as f:
                json.dump(missing_all, f, indent=2)
            print(f"[{node}] -> wrote {len(missing_all)} missing records to {out_path}")
        else:
            print(f"[{node}] -> nothing missing, fully synced.")
        print("-" * 70)

    print("\nDone. Point a submission_order.yaml at payloads/missing/*.json to resubmit only the gaps.")


if __name__ == "__main__":
    main()